apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountmcpserver-deployment
  labels:
    app: accountmcpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountmcpserver
  template:
    metadata:
      # kubectl rollout history deployment/accountmcpserver-deployment
      annotations:
        kubernetes.io/change-cause: "Updated image to #{VERSION}#"
      labels:
        app: accountmcpserver
    spec:
      containers:
        - name: accountmcpserver
          image: agilesolutions/accountmcpserver:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 15
          lifecycle:
            preStop:
              httpGet:
                path: /unhealthy
                port: http
#          terminationGracePeriodSeconds: 10
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: false
          env:
            - name: LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
      imagePullSecrets:
        - name: my-acr-secret
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
---
apiVersion: v1
kind: Service
metadata:
  name: accountmcpserver-loadbalancer-service
  labels:
    app: accountmcpserver
spec:
  type: LoadBalancer
  selector:
    app: accountmcpserver
  ports:
    - port: 80
      targetPort: 80